name: Build using Cloud Build

on:
  push:
    branches:
    - 'main'

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  SERVICE_NAME: ${{ secrets.RUN_SERVICE }}

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: service
      run: echo ::set-output name=service::run-envvars-$GITHUB_SHA
    - name: Checkout
      uses: actions/checkout@v3

    # Alternative option - authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.RUN_SA_KEY }}'

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"

    - name: Deploy service to Cloud Run
      id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        service: ${{ secrets.RUN_SERVICE }}
        image: "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
        secrets: |
          INDOME_DB_NAME=INDOME_DB_NAME:latest
          INDOME_MONGODB_URI=INDOME_MONGODB_URI:latest
          INDOME_GCP_BUCKET=INDOME_GCP_BUCKET:latest
          INDOME_ADMIN_SECRET=INDOME_ADMIN_SECRET:latest
          GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest
          GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest
          GOOGLE_REFRESH_TOKEN=GOOGLE_REFRESH_TOKEN:latest        
